import { defineConfig } from 'orval'
import { config } from 'dotenv'

config({ path: '.env.local' })
config({ path: '.env' })

export default defineConfig({
  compliance: {
    input: {
      target: process.env.NEXT_PUBLIC_API_URL
        ? `${process.env.NEXT_PUBLIC_API_URL.replace(/\/$/, '')}/api/schema/`
        : 'https://test.compliance.dstax.com/api/schema/',
    },
    output: {
      target: 'src/api/generated/',
      client: 'react-query',
      mode: 'tags-split',
      schemas: 'src/models/',
      prettier: true,
      override: {
        mutator: {
          path: 'src/api/mutator/custom-instance.ts',
          name: 'customInstance',
        },
        zod: {
          generate: {
            response: true,
            body: true,
            param: true,
            query: true,
            header: false,
          },
        },
        header: (info) => [
          `Generated by orval`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: 'prettier --write',
    },
  },
})
