import type { FSItem, TabValue } from './types'

export const MOCK_DOCUMENTS: FSItem[] = [
  {
    id: '1',
    name: 'Annual Reports',
    type: 'folder',
    dateModified: '2024-03-15',
    createdAt: '2024-01-10',
    createdBy: 'John Doe',
    modifiedBy: 'Jane Smith',
  },
  {
    id: '2',
    name: 'Tax Documents 2023',
    type: 'folder',
    dateModified: '2024-02-20',
    createdAt: '2024-01-15',
    createdBy: 'John Doe',
    modifiedBy: 'John Doe',
  },
  {
    id: '3',
    name: 'Client Forms',
    type: 'folder',
    dateModified: '2024-03-01',
    createdAt: '2024-02-01',
    createdBy: 'Admin',
    modifiedBy: 'Admin',
  },
  {
    id: '4',
    name: 'Q1_Report.pdf',
    type: 'pdf',
    dateModified: '2024-03-10',
    size: '2.4 MB',
    createdAt: '2024-03-10',
    createdBy: 'Jane Smith',
    modifiedBy: 'Jane Smith',
  },
  {
    id: '5',
    name: 'Client_Data.csv',
    type: 'csv',
    dateModified: '2024-03-08',
    size: '1.1 MB',
    createdAt: '2024-03-08',
    createdBy: 'Admin',
    modifiedBy: 'Admin',
  },
  {
    id: '6',
    name: 'Financial_Summary.xlsx',
    type: 'xlsx',
    dateModified: '2024-03-05',
    size: '3.7 MB',
    createdAt: '2024-03-01',
    createdBy: 'John Doe',
    modifiedBy: 'Jane Smith',
  },
  {
    id: '7',
    name: 'Compliance_Report.pdf',
    type: 'pdf',
    dateModified: '2024-02-28',
    size: '5.2 MB',
    createdAt: '2024-02-15',
    createdBy: 'Jane Smith',
    modifiedBy: 'Jane Smith',
  },
]

export const MOCK_ARCHIVED: FSItem[] = [
  {
    id: 'a1',
    name: 'Returns 2022',
    type: 'folder',
    dateModified: '2023-04-10',
    createdAt: '2022-12-01',
    createdBy: 'Admin',
    modifiedBy: 'Admin',
  },
  {
    id: 'a2',
    name: 'Returns 2021',
    type: 'folder',
    dateModified: '2022-04-15',
    createdAt: '2021-12-01',
    createdBy: 'Admin',
    modifiedBy: 'Admin',
  },
  {
    id: 'a3',
    name: 'Archive_2022_Final.pdf',
    type: 'pdf',
    dateModified: '2023-01-05',
    size: '8.1 MB',
    createdAt: '2023-01-05',
    createdBy: 'John Doe',
    modifiedBy: 'John Doe',
  },
]

export const MOCK_CLIENT_DATA: FSItem[] = [
  {
    id: 'c1',
    name: 'Client Records',
    type: 'folder',
    dateModified: '2024-04-01',
    createdAt: '2024-01-01',
    createdBy: 'Admin',
    modifiedBy: 'Admin',
  },
  {
    id: 'c2',
    name: 'Imports',
    type: 'folder',
    dateModified: '2024-03-28',
    createdAt: '2024-02-10',
    createdBy: 'Jane Smith',
    modifiedBy: 'Jane Smith',
  },
  {
    id: 'c3',
    name: 'client_export_march.csv',
    type: 'csv',
    dateModified: '2024-03-31',
    size: '4.2 MB',
    createdAt: '2024-03-31',
    createdBy: 'Jane Smith',
    modifiedBy: 'Jane Smith',
  },
  {
    id: 'c4',
    name: 'data_template.xlsx',
    type: 'xlsx',
    dateModified: '2024-03-20',
    size: '0.9 MB',
    createdAt: '2024-01-15',
    createdBy: 'Admin',
    modifiedBy: 'Admin',
  },
]

export const TAB_DATA: Record<TabValue, FSItem[]> = {
  'client-documents': MOCK_DOCUMENTS,
  'archived-returns': MOCK_ARCHIVED,
  'client-data': MOCK_CLIENT_DATA,
}
