import type { SpreadsheetColumn } from '@/components/spreadsheet/SpreadsheetGrid'

// --- Types ---

export interface TVRClient {
  id: string
  clientName: string
  legalEntities: string[]
}

export interface TVRRow {
  id: string
  legalEntity: string
  jurisdiction: string
  taxType: string
  filingFrequency: string
  filingMethod: string
  dueDate: string
  deTime: string
  glAmount: number
  salesTaxExtractAmount: number
  amountToAdjust: number
  manualAdjustment: number
  useTax: number
  nonMonthlyCarriedForwardPrior: number
  nonMonthlyCarriedForwardFuture: number
  creditsCarriedForwardPrior: number
  creditsCarriedForwardFuture: number
  localAdjustment: number
  grossDue: number
  prepaymentCredit: number
  prepaymentDue: number
  vendorsDiscount: number
  businessAndOccupationTax: number
  rounding: number
  currencyConverted: number
  netDue: number
  currencyCode: string
  amountToFund: number
  statusConfirmationNumber: string
  paymentConfirmationNumber: string
  paymentAmount: number
  filingDate: string
  paymentDate: string
  clientComment: string
  dstaxComment: string
  isActive: boolean
}

// --- Mock Clients ---

export const mockClients: TVRClient[] = [
  {
    id: '1',
    clientName: 'Acme Corp',
    legalEntities: ['Acme US LLC', 'Acme EU GmbH', 'Acme Asia Pte Ltd'],
  },
  {
    id: '2',
    clientName: 'Techy Inc',
    legalEntities: ['Techy NY Corp', 'Techy UK Ltd'],
  },
  {
    id: '3',
    clientName: 'Global Holdings',
    legalEntities: [
      'Global US Inc',
      'Global Canada Corp',
      'Global Mexico SA',
      'Global Brazil Ltda',
    ],
  },
  {
    id: '4',
    clientName: 'Summit Financial',
    legalEntities: ['Summit NA LLC', 'Summit EU BV'],
  },
  {
    id: '5',
    clientName: 'Apex Manufacturing',
    legalEntities: ['Apex US LLC'],
  },
]

// --- Mock TVR Rows per Client ---

export const mockTvrData: Record<string, TVRRow[]> = {
  '1': [
    {
      id: 'tvr-1-1',
      legalEntity: 'Acme US LLC',
      jurisdiction: 'CA',
      taxType: 'Sales Tax',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-20',
      deTime: '17:00',
      glAmount: 50000.0,
      salesTaxExtractAmount: 50000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 1500.0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 51500.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 250.0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 51250.0,
      currencyCode: 'USD',
      amountToFund: 51250.0,
      statusConfirmationNumber: 'CONF-12345',
      paymentConfirmationNumber: 'PAY-67890',
      paymentAmount: 51250.0,
      filingDate: '2026-04-18',
      paymentDate: '2026-04-18',
      clientComment: 'All good',
      dstaxComment: 'Verified',
      isActive: true,
    },
    {
      id: 'tvr-1-2',
      legalEntity: 'Acme US LLC',
      jurisdiction: 'NY',
      taxType: 'Use Tax',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-20',
      deTime: '17:00',
      glAmount: 32000.0,
      salesTaxExtractAmount: 32000.0,
      amountToAdjust: 200.0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 32200.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 32200.0,
      currencyCode: 'USD',
      amountToFund: 32200.0,
      statusConfirmationNumber: 'CONF-22345',
      paymentConfirmationNumber: 'PAY-22890',
      paymentAmount: 32200.0,
      filingDate: '2026-04-18',
      paymentDate: '2026-04-18',
      clientComment: '',
      dstaxComment: 'Verified',
      isActive: true,
    },
    {
      id: 'tvr-1-3',
      legalEntity: 'Acme EU GmbH',
      jurisdiction: 'DE',
      taxType: 'VAT',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-10',
      deTime: '23:59',
      glAmount: 120000.0,
      salesTaxExtractAmount: 120000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 5000.0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 120000.0,
      prepaymentCredit: 5000.0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 115000.0,
      currencyCode: 'EUR',
      amountToFund: 115000.0,
      statusConfirmationNumber: 'CONF-EU-001',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: 'Pending review',
      isActive: true,
    },
    {
      id: 'tvr-1-4',
      legalEntity: 'Acme Asia Pte Ltd',
      jurisdiction: 'SG',
      taxType: 'GST',
      filingFrequency: 'Quarterly',
      filingMethod: 'E-File',
      dueDate: '2026-04-30',
      deTime: '23:59',
      glAmount: 85000.0,
      salesTaxExtractAmount: 85000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 85000.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 85000.0,
      currencyCode: 'SGD',
      amountToFund: 85000.0,
      statusConfirmationNumber: 'Pending',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: '',
      isActive: true,
    },
  ],
  '2': [
    {
      id: 'tvr-2-1',
      legalEntity: 'Techy NY Corp',
      jurisdiction: 'NY',
      taxType: 'Use Tax',
      filingFrequency: 'Quarterly',
      filingMethod: 'Paper',
      dueDate: '2026-04-20',
      deTime: '17:00',
      glAmount: 25000.0,
      salesTaxExtractAmount: 25000.0,
      amountToAdjust: 500.0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 25500.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 25500.0,
      currencyCode: 'USD',
      amountToFund: 25500.0,
      statusConfirmationNumber: 'Pending',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: 'Pending review',
      isActive: true,
    },
    {
      id: 'tvr-2-2',
      legalEntity: 'Techy UK Ltd',
      jurisdiction: 'GB',
      taxType: 'VAT',
      filingFrequency: 'Quarterly',
      filingMethod: 'E-File',
      dueDate: '2026-04-07',
      deTime: '23:59',
      glAmount: 78000.0,
      salesTaxExtractAmount: 78000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 2000.0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 78000.0,
      prepaymentCredit: 2000.0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 76000.0,
      currencyCode: 'GBP',
      amountToFund: 76000.0,
      statusConfirmationNumber: 'CONF-UK-001',
      paymentConfirmationNumber: 'PAY-UK-001',
      paymentAmount: 76000.0,
      filingDate: '2026-04-05',
      paymentDate: '2026-04-05',
      clientComment: 'Confirmed',
      dstaxComment: 'Filed and paid',
      isActive: true,
    },
  ],
  '3': [
    {
      id: 'tvr-3-1',
      legalEntity: 'Global US Inc',
      jurisdiction: 'TX',
      taxType: 'Sales Tax',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-20',
      deTime: '17:00',
      glAmount: 95000.0,
      salesTaxExtractAmount: 95000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 2500.0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 97500.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 500.0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 97000.0,
      currencyCode: 'USD',
      amountToFund: 97000.0,
      statusConfirmationNumber: 'CONF-33001',
      paymentConfirmationNumber: 'PAY-33001',
      paymentAmount: 97000.0,
      filingDate: '2026-04-18',
      paymentDate: '2026-04-18',
      clientComment: '',
      dstaxComment: 'Verified',
      isActive: true,
    },
    {
      id: 'tvr-3-2',
      legalEntity: 'Global Canada Corp',
      jurisdiction: 'ON',
      taxType: 'GST',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-30',
      deTime: '23:59',
      glAmount: 62000.0,
      salesTaxExtractAmount: 62000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 62000.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 62000.0,
      currencyCode: 'CAD',
      amountToFund: 62000.0,
      statusConfirmationNumber: 'Pending',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: '',
      isActive: true,
    },
    {
      id: 'tvr-3-3',
      legalEntity: 'Global Mexico SA',
      jurisdiction: 'MX',
      taxType: 'VAT',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-17',
      deTime: '23:59',
      glAmount: 45000.0,
      salesTaxExtractAmount: 45000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 45000.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 45000.0,
      currencyCode: 'MXN',
      amountToFund: 45000.0,
      statusConfirmationNumber: 'CONF-MX-001',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: 'Under review',
      isActive: true,
    },
    {
      id: 'tvr-3-4',
      legalEntity: 'Global Brazil Ltda',
      jurisdiction: 'BR',
      taxType: 'VAT',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-25',
      deTime: '23:59',
      glAmount: 38000.0,
      salesTaxExtractAmount: 38000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 38000.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 38000.0,
      currencyCode: 'BRL',
      amountToFund: 38000.0,
      statusConfirmationNumber: 'Pending',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: '',
      isActive: true,
    },
  ],
  '4': [
    {
      id: 'tvr-4-1',
      legalEntity: 'Summit NA LLC',
      jurisdiction: 'FL',
      taxType: 'Sales Tax',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-20',
      deTime: '17:00',
      glAmount: 42000.0,
      salesTaxExtractAmount: 42000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 800.0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 42800.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 100.0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 42700.0,
      currencyCode: 'USD',
      amountToFund: 42700.0,
      statusConfirmationNumber: 'CONF-44001',
      paymentConfirmationNumber: 'PAY-44001',
      paymentAmount: 42700.0,
      filingDate: '2026-04-18',
      paymentDate: '2026-04-18',
      clientComment: '',
      dstaxComment: 'Verified',
      isActive: true,
    },
    {
      id: 'tvr-4-2',
      legalEntity: 'Summit EU BV',
      jurisdiction: 'NL',
      taxType: 'VAT',
      filingFrequency: 'Quarterly',
      filingMethod: 'E-File',
      dueDate: '2026-04-30',
      deTime: '23:59',
      glAmount: 88000.0,
      salesTaxExtractAmount: 88000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 3000.0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 88000.0,
      prepaymentCredit: 3000.0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 85000.0,
      currencyCode: 'EUR',
      amountToFund: 85000.0,
      statusConfirmationNumber: 'Pending',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: 'Pending review',
      isActive: true,
    },
  ],
  '5': [
    {
      id: 'tvr-5-1',
      legalEntity: 'Apex US LLC',
      jurisdiction: 'WA',
      taxType: 'Sales Tax',
      filingFrequency: 'Monthly',
      filingMethod: 'E-File',
      dueDate: '2026-04-25',
      deTime: '17:00',
      glAmount: 18000.0,
      salesTaxExtractAmount: 18000.0,
      amountToAdjust: 0,
      manualAdjustment: 0,
      useTax: 0,
      nonMonthlyCarriedForwardPrior: 0,
      nonMonthlyCarriedForwardFuture: 0,
      creditsCarriedForwardPrior: 0,
      creditsCarriedForwardFuture: 0,
      localAdjustment: 0,
      grossDue: 18000.0,
      prepaymentCredit: 0,
      prepaymentDue: 0,
      vendorsDiscount: 0,
      businessAndOccupationTax: 750.0,
      rounding: 0,
      currencyConverted: 0,
      netDue: 18750.0,
      currencyCode: 'USD',
      amountToFund: 18750.0,
      statusConfirmationNumber: 'CONF-55001',
      paymentConfirmationNumber: '',
      paymentAmount: 0,
      filingDate: '',
      paymentDate: '',
      clientComment: '',
      dstaxComment: 'B&O tax added',
      isActive: true,
    },
  ],
}

// --- Filter helpers ---

export function getFilterOptions(rows: TVRRow[]) {
  const unique = (arr: string[]) =>
    Array.from(new Set(arr.filter(Boolean))).map((v) => ({
      value: v,
      label: v,
    }))

  return {
    legalEntities: unique(rows.map((r) => r.legalEntity)),
    jurisdictions: unique(rows.map((r) => r.jurisdiction)),
    taxTypes: unique(rows.map((r) => r.taxType)),
    filingFrequencies: unique(rows.map((r) => r.filingFrequency)),
    filingTypes: unique(rows.map((r) => r.filingMethod)),
  }
}

// --- Spreadsheet column config ---

const currencyCol = (id: string, label: string): SpreadsheetColumn => ({
  id,
  label,
  type: 'currency',
  width: 160,
})

export const gridColumns: SpreadsheetColumn[] = [
  { id: 'legalEntity', label: 'Legal Entity', width: 180, readOnly: true },
  { id: 'jurisdiction', label: 'Jurisdiction', width: 110, readOnly: true },
  { id: 'taxType', label: 'Tax Type', width: 120 },
  { id: 'filingFrequency', label: 'Filing Frequency', width: 140 },
  { id: 'filingMethod', label: 'Filing Method', width: 120 },
  { id: 'dueDate', label: 'Due Date', type: 'date', width: 120 },
  { id: 'deTime', label: 'De Time', width: 100 },
  currencyCol('glAmount', 'G/L Amount'),
  currencyCol('salesTaxExtractAmount', 'Sales Tax Extract Amount'),
  currencyCol('amountToAdjust', 'Amount to Adjust'),
  currencyCol('manualAdjustment', 'Manual Adjustment (Client Provided)'),
  currencyCol('useTax', 'Use Tax (Sales & Use Tax Extract)'),
  currencyCol(
    'nonMonthlyCarriedForwardPrior',
    'Non-Monthly CF from Prior Periods'
  ),
  currencyCol(
    'nonMonthlyCarriedForwardFuture',
    'Non-Monthly CF to Future Periods'
  ),
  currencyCol('creditsCarriedForwardPrior', 'Credits CF from Prior Periods'),
  currencyCol('creditsCarriedForwardFuture', 'Credits CF to Future Periods'),
  currencyCol('localAdjustment', 'Local Adjustment'),
  currencyCol('grossDue', 'Gross Due'),
  currencyCol('prepaymentCredit', 'Prepayment Credit'),
  currencyCol('prepaymentDue', 'Prepayment Due'),
  currencyCol('vendorsDiscount', "Vendor's Discount"),
  currencyCol('businessAndOccupationTax', 'Business & Occupation Tax'),
  currencyCol('rounding', 'Rounding'),
  currencyCol('currencyConverted', 'Currency Converted'),
  currencyCol('netDue', 'Net Due'),
  { id: 'currencyCode', label: 'Currency Code', width: 120 },
  currencyCol('amountToFund', 'Amount to Fund'),
  {
    id: 'statusConfirmationNumber',
    label: 'Status/Confirmation #',
    width: 180,
  },
  {
    id: 'paymentConfirmationNumber',
    label: 'Payment Confirmation #',
    width: 180,
  },
  currencyCol('paymentAmount', 'Payment Amount'),
  { id: 'filingDate', label: 'Filing Date', type: 'date', width: 120 },
  { id: 'paymentDate', label: 'Payment Date', type: 'date', width: 120 },
  { id: 'clientComment', label: 'Client Comment', width: 200 },
  { id: 'dstaxComment', label: 'DSTax Comment', width: 200 },
  {
    id: 'isActive',
    label: 'Active?',
    type: 'checkbox',
    width: 80,
    align: 'center',
  },
]

// Only these columns are editable on the TVR detail screen
export const editableTvrColumns: string[] = [
  'glAmount',
  'salesTaxExtractAmount',
  'manualAdjustment',
  'useTax',
  'creditsCarriedForwardPrior',
  'creditsCarriedForwardFuture',
  'localAdjustment',
  'prepaymentDue',
  'vendorsDiscount',
  'businessAndOccupationTax',
  'rounding',
  'currencyConverted',
  'statusConfirmationNumber',
  'paymentConfirmationNumber',
  'paymentAmount',
  'filingDate',
  'paymentDate',
  'clientComment',
  'dstaxComment',
  'isActive',
]
