/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiCoreLegalEntityListParams = {
  client?: number
  /**
   * Multiple values may be separated by commas.
   */
  client__in?: number[]
  id?: number
  /**
   * Multiple values may be separated by commas.
   */
  id__in?: number[]
  is_active?: boolean
  name?: string
  name__icontains?: string
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string
  /**
   * A page number within the paginated result set.
   */
  page?: number
  /**
   * Number of results to return per page.
   */
  page_size?: number
}
