/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiCoreUserListRole =
  (typeof ApiCoreUserListRole)[keyof typeof ApiCoreUserListRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiCoreUserListRole = {
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  CLIENT_STAFF: 'CLIENT_STAFF',
  DSTAX_ADMIN: 'DSTAX_ADMIN',
  DSTAX_PREPARER: 'DSTAX_PREPARER',
} as const
