/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiCoreClientListParams = {
  id?: number
  /**
   * Multiple values may be separated by commas.
   */
  id__in?: number[]
  is_active?: boolean
  name?: string
  name__icontains?: string
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string
}
