/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ApiCoreUserListRole } from './apiCoreUserListRole'

export type ApiCoreUserListParams = {
  assigned_legal_entities?: number[]
  assigned_legal_entities_names?: string
  email?: string
  email__icontains?: string
  id?: number
  /**
   * Multiple values may be separated by commas.
   */
  id__in?: number[]
  is_active?: boolean
  managed_client?: number
  /**
   * Multiple values may be separated by commas.
   */
  managed_client__in?: number[]
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string
  /**
   * A page number within the paginated result set.
   */
  page?: number
  /**
   * Number of results to return per page.
   */
  page_size?: number
  /**
   * * `DSTAX_ADMIN` - DSTax_Admin
   * `DSTAX_PREPARER` - DSTax_Preparer
   * `CLIENT_ADMIN` - Client_Admin
   * `CLIENT_STAFF` - Client_Staff
   */
  role?: ApiCoreUserListRole
}
