/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiCoreSupportTicketListParams = {
  client?: number
  created_by?: number
  id?: number
  /**
   * Multiple values may be separated by commas.
   */
  id__in?: number[]
  legal_entity?: number
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string
  /**
   * A page number within the paginated result set.
   */
  page?: number
  /**
   * Number of results to return per page.
   */
  page_size?: number
  title?: string
  title__icontains?: string
}
