/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ApiCoreUserListRole } from './apiCoreUserListRole'

export type ApiCoreUserListParams = {
  assigned_legal_entities?: string
  id?: number
  /**
   * Multiple values may be separated by commas.
   */
  id__in?: number[]
  managed_client?: number
  /**
   * Multiple values may be separated by commas.
   */
  managed_client__in?: number[]
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string
  /**
   * * `DSTAX_ADMIN` - DSTax_Admin
   * `DSTAX_PREPARER` - DSTax_Preparer
   * `CLIENT_ADMIN` - Client_Admin
   * `CLIENT_STAFF` - Client_Staff
   */
  role?: ApiCoreUserListRole
}
