/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ApiSchemaRetrieveFormat } from './apiSchemaRetrieveFormat'
import type { ApiSchemaRetrieveLang } from './apiSchemaRetrieveLang'

export type ApiSchemaRetrieveParams = {
  format?: ApiSchemaRetrieveFormat
  lang?: ApiSchemaRetrieveLang
}
