/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiSchemaRetrieveFormat =
  (typeof ApiSchemaRetrieveFormat)[keyof typeof ApiSchemaRetrieveFormat]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiSchemaRetrieveFormat = {
  json: 'json',
  yaml: 'yaml',
} as const
