/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiTaxComplianceTvrPeriodActivesListWorkflowStatus =
  (typeof ApiTaxComplianceTvrPeriodActivesListWorkflowStatus)[keyof typeof ApiTaxComplianceTvrPeriodActivesListWorkflowStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiTaxComplianceTvrPeriodActivesListWorkflowStatus = {
  DRAFT: 'DRAFT',
  FUNDING_RECEIVED: 'FUNDING_RECEIVED',
  PREPARED: 'PREPARED',
  PUBLISHED: 'PUBLISHED',
  REVIEW_COMMENTS: 'REVIEW_COMMENTS',
} as const
