/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiTaxComplianceJurisdictionLevelListParams = {
  created_at?: string
  created_at__gte?: string
  created_at__lte?: string
  id?: number
  /**
   * Multiple values may be separated by commas.
   */
  id__in?: number[]
  name?: string
  name__icontains?: string
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string
}
