/**
 * Generated by orval
 * Do not edit manually.
 */

export type ApiTaxCompliancePrepaymentMethodsListParams = {
  created_at?: string
  created_at__gte?: string
  created_at__lte?: string
  id?: number
  /**
   * Multiple values may be separated by commas.
   */
  id__in?: number[]
  jurisdiction?: number
  /**
   * Multiple values may be separated by commas.
   */
  jurisdiction__in?: number[]
  method_description?: string
  method_description__icontains?: string
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string
}
