/**
 * Generated by orval
 * Do not edit manually.
 */

export interface Jurisdiction {
  readonly id: number
  /** @maxLength 255 */
  name: string
  level: number
  readonly level_name: string
  /** @nullable */
  due_date_time?: string | null
}
