/**
 * Generated by orval
 * Do not edit manually.
 */
import type { RoleEnum } from './roleEnum'
import type { SimpleClient } from './simpleClient'
import type { SimpleLegalEntity } from './simpleLegalEntity'

export interface Me {
  readonly id: number
  /** @maxLength 254 */
  email: string
  /** @maxLength 150 */
  first_name?: string
  /** @maxLength 150 */
  last_name?: string
  role: RoleEnum
  readonly managed_client: SimpleClient
  readonly assigned_legal_entities: readonly SimpleLegalEntity[]
  readonly is_dstax_admin: boolean
  readonly is_dstax_preparer: boolean
  readonly is_client_admin: boolean
  readonly is_client_staff: boolean
}
