/**
 * Generated by orval
 * Do not edit manually.
 */
import type { TVRRecordMarkPreparedItem } from './tVRRecordMarkPreparedItem'

export interface PaginatedTVRRecordMarkPreparedItemList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: TVRRecordMarkPreparedItem[]
}
