/**
 * Generated by orval
 * Do not edit manually.
 */
import type { FilingType } from './filingType'

export interface PaginatedFilingTypeList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: FilingType[]
}
