/**
 * Generated by orval
 * Do not edit manually.
 */
import type { TVRRecordClientCommentItem } from './tVRRecordClientCommentItem'

export interface PaginatedTVRRecordClientCommentItemList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: TVRRecordClientCommentItem[]
}
