/**
 * Generated by orval
 * Do not edit manually.
 */
import type { LegalEntity } from './legalEntity'

export interface PaginatedLegalEntityList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: LegalEntity[]
}
