/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Jurisdiction } from './jurisdiction'

export interface PaginatedJurisdictionList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: Jurisdiction[]
}
