/**
 * Generated by orval
 * Do not edit manually.
 */
import type { JurisdictionLevel } from './jurisdictionLevel'

export interface PaginatedJurisdictionLevelList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: JurisdictionLevel[]
}
