/**
 * Generated by orval
 * Do not edit manually.
 */
import type { TaxType } from './taxType'

export interface PaginatedTaxTypeList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: TaxType[]
}
