/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Client } from './client'

export interface PaginatedClientList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: Client[]
}
