/**
 * Generated by orval
 * Do not edit manually.
 */
import type { TVRRecord } from './tVRRecord'

export interface PaginatedTVRRecordList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: TVRRecord[]
}
