/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PrepaymentMethod } from './prepaymentMethod'

export interface PaginatedPrepaymentMethodList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: PrepaymentMethod[]
}
