/**
 * Generated by orval
 * Do not edit manually.
 */
import type { TVRRecordCommentItem } from './tVRRecordCommentItem'

export interface PaginatedTVRRecordCommentItemList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: TVRRecordCommentItem[]
}
