/**
 * Generated by orval
 * Do not edit manually.
 */
import type { FilingFrequency } from './filingFrequency'

export interface PaginatedFilingFrequencyList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: FilingFrequency[]
}
