/**
 * Generated by orval
 * Do not edit manually.
 */
import type { SupportTicket } from './supportTicket'

export interface PaginatedSupportTicketList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: SupportTicket[]
}
