/**
 * Generated by orval
 * Do not edit manually.
 */
import type { User } from './user'

export interface PaginatedUserList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: User[]
}
