/**
 * Generated by orval
 * Do not edit manually.
 */
import type { TVRPeriod } from './tVRPeriod'

export interface PaginatedTVRPeriodList {
  count: number
  /** @nullable */
  next?: string | null
  /** @nullable */
  previous?: string | null
  results: TVRPeriod[]
}
