/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Jurisdiction } from './jurisdiction'

export interface PrepaymentMethod {
  readonly id: number
  readonly jurisdiction: Jurisdiction
  /** @maxLength 255 */
  method_description: string
  jurisdiction_id: number
}
