/**
 * Generated by orval
 * Do not edit manually.
 */
import type { SimpleClient } from './simpleClient'
import type { WorkflowStatusEnum } from './workflowStatusEnum'

export interface SimpleTVRPeriod {
  readonly id: number
  readonly client: SimpleClient
  readonly period_month: number
  readonly period_year: number
  readonly workflow_status: WorkflowStatusEnum
  readonly is_expired: boolean
}
