/**
 * Generated by orval
 * Do not edit manually.
 */
import type { SimpleClient } from './simpleClient'

export interface SimpleLegalEntity {
  readonly id: number
  readonly client: SimpleClient
  readonly name: string
  readonly is_active: boolean
}
