/**
 * Generated by orval
 * Do not edit manually.
 */
import type { SimpleClient } from './simpleClient'

export interface SimpleLegalEntity {
  readonly id: number
  /** @maxLength 255 */
  name: string
  readonly client: SimpleClient
}
