/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Client } from './client'
import type { LegalEntity } from './legalEntity'
import type { SimpleUser } from './simpleUser'

export interface SupportTicket {
  readonly id: number
  readonly client: Client
  /** @nullable */
  client_id?: number | null
  readonly legal_entity: LegalEntity
  /** @nullable */
  legal_entity_id?: number | null
  /** @maxLength 255 */
  title: string
  description: string
  readonly created_by: SimpleUser
}
