/**
 * Generated by orval
 * Do not edit manually.
 */
import type { WorkflowStatusEnum } from './workflowStatusEnum'

export interface TVRPeriodFundingReceived {
  readonly id: number
  readonly workflow_status: WorkflowStatusEnum
}
