/**
 * Generated by orval
 * Do not edit manually.
 */

export interface TVRRecordMarkPreparedItem {
  id: number
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  gl_amount?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  sales_tax_extract?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  amount_to_adjust?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  manual_adjustment?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  use_tax?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  nmr_cf_prior?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  nmr_cf_future?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  credits_cf_prior?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  credits_cf_future?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  local_adjustment?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  gross_due?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  prepayment_credit?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  prepayment_due?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  vendors_discount?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  bo_tax?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  rounding?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  currency_converted?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  net_due?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  amount_to_fund?: string
  /** @pattern ^-?\d{0,13}(?:\.\d{0,2})?$ */
  payment_amount?: string
  /** @maxLength 255 */
  status_conf_num?: string
  /** @maxLength 255 */
  payment_conf_num?: string
  filing_date?: string
  payment_date?: string
  dstax_comment?: string
  client_comment?: string
}
