/**
 * Generated by orval
 * Do not edit manually.
 */
import type { RoleEnum } from './roleEnum'
import type { LegalEntity } from './legalEntity'

export interface User {
  role: RoleEnum
  /** @nullable */
  managed_client?: number | null
  readonly assigned_legal_entities: readonly LegalEntity[]
  assigned_legal_entity_ids: number[]
}
