/**
 * Generated by orval
 * Do not edit manually.
 */
import type { RoleEnum } from './roleEnum'
import type { SimpleClient } from './simpleClient'
import type { SimpleLegalEntity } from './simpleLegalEntity'

export interface User {
  readonly id: number
  /** @maxLength 254 */
  email: string
  password: string
  /** Designates whether this user should be treated as active. Unselect this instead of deleting accounts. */
  is_active?: boolean
  role: RoleEnum
  readonly managed_client: SimpleClient
  /** @nullable */
  managed_client_id?: number | null
  readonly assigned_legal_entities: readonly SimpleLegalEntity[]
  assigned_legal_entity_ids?: number[]
}
