/**
 * Generated by orval
 * Do not edit manually.
 */

/**
 * * `DRAFT` - Draft
 * `PREPARED` - Prepared
 * `REVIEW_COMMENTS` - Review Comments
 * `PUBLISHED` - Published
 * `FUNDING_RECEIVED` - Funding Received
 */
export type WorkflowStatusEnum =
  (typeof WorkflowStatusEnum)[keyof typeof WorkflowStatusEnum]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowStatusEnum = {
  DRAFT: 'DRAFT',
  PREPARED: 'PREPARED',
  REVIEW_COMMENTS: 'REVIEW_COMMENTS',
  PUBLISHED: 'PUBLISHED',
  FUNDING_RECEIVED: 'FUNDING_RECEIVED',
} as const
