#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then
  echo "❌ You cannot commit directly to the main branch!"
  exit 1
fi

yarn type-check && yarn lint-staged
